local fmt = require("lua.rs-macro-fmt")
describe("rs-macro-fmt", function()
    describe("count_leading_ws", function()
        it("should be 3", function()
            local count = fmt._private.count_leading_ws("   232")
            assert.are.equal(count, 3)
        end)
        it("should be 0", function()
            local count = fmt._private.count_leading_ws("232")
            assert.are.equal(count, 0)
        end)
        it("should be 0", function()
            local count = fmt._private.count_leading_ws("")
            assert.are.equal(count, 0)
        end)
        it("should be 3", function()
            local count = fmt._private.count_leading_ws("   ")
            assert.are.equal(count, 3)
        end)
    end)
end)
